In [2]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 


In [5]:
cares=pd.read_csv('cars.csv',delimiter=';')

In [6]:
cares.head()

Car     MPG Cylinders Displacement Horsepower  \
0                     STRING  DOUBLE       INT       DOUBLE     DOUBLE   
1  Chevrolet Chevelle Malibu    18.0         8        307.0      130.0   
2          Buick Skylark 320    15.0         8        350.0      165.0   
3         Plymouth Satellite    18.0         8        318.0      150.0   
4              AMC Rebel SST    16.0         8        304.0      150.0   

   Weight Acceleration Model Origin  
0  DOUBLE       DOUBLE   INT    CAT  
1   3504.         12.0    70     US  
2   3693.         11.5    70     US  
3   3436.         11.0    70     US  
4   3433.         12.0    70     US

In [20]:
#nombre de lignes et colonnes 
cares.shape

(407, 9)

In [23]:
cares.dtypes

Car             object
MPG             object
Cylinders       object
Displacement    object
Horsepower      object
Weight          object
Acceleration    object
Model           object
Origin          object
dtype: object

In [24]:
cares.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 407 entries, 0 to 406
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Car           407 non-null    object
 1   MPG           407 non-null    object
 2   Cylinders     407 non-null    object
 3   Displacement  407 non-null    object
 4   Horsepower    407 non-null    object
 5   Weight        407 non-null    object
 6   Acceleration  407 non-null    object
 7   Model         407 non-null    object
 8   Origin        407 non-null    object
dtypes: object(9)
memory usage: 28.7+ KB


In [25]:
cares.describe()

Car   MPG Cylinders Displacement Horsepower Weight  \
count              407   407       407          407        407    407   
unique             309   131         6           84         95    357   
top     Toyota Corolla  13.0         4        97.00      150.0  2130.   
freq                 9    20       207           22         22      4   

       Acceleration Model Origin  
count           407   407    407  
unique           98    14      4  
top            14.5    73     US  
freq             23    40    254

In [11]:
b=np.array([0,-5,1,4.5,2])

In [12]:
a=np.array([1,2,3,4])

In [13]:
a[0]

1

In [15]:
b[0]

0.0

In [32]:
##Afficher tous les valeurs
a[0:]

array([1, 2, 3, 4])

In [33]:
##afficher tous les valeurs à partir de l'indice 1
a[1:]

array([2, 3, 4])

In [35]:
##afficher tous les valeurs à partir de l'indice 3
a[3:]

array([4])

In [39]:
#affichier toujours n-1 elment
a[1:3]

array([2, 3])

In [16]:
#déclration simple liste n'appertient pas à pandas 
c=[1,2,3,4]

In [45]:
c[1]

2

In [46]:
c[1:3]

[2, 3]

In [48]:
a.dtype

dtype('int32')

In [50]:
b.dtype

dtype('float64')

In [51]:
#  le résultat est erreur de syntaxe car  la fonction dtype compatible uniquement avec nmpy, 
c.dtype

AttributeError: 'list' object has no attribute 'dtype'

In [52]:
A = np.array([
    ['a', 'b', 'c'],
    ['d', 'e', 'f'],
    ['g', 'h', 'i']
])

In [53]:
## Afficher toutes la matrices 
A[:,:]

array([['a', 'b', 'c'],
       ['d', 'e', 'f'],
       ['g', 'h', 'i']], dtype='<U1')

In [55]:
#Afficher les 3lignes et le premier colone 
A[:,1:2]

array([['b'],
       ['e'],
       ['h']], dtype='<U1')

In [60]:
# Afficher le  le 2ème ligne  et 2ème colone 
A[1:2,1:2]

array([['e']], dtype='<U1')