In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 


In [13]:
a=np.arange(5)



In [5]:
a

array([0, 1, 2, 3, 4])

In [11]:
a+20

array([20, 21, 22, 23, 24])

In [12]:
a+100

array([100, 101, 102, 103, 104])

In [16]:
a*2

array([0, 2, 4, 6, 8])

In [17]:
a*11

array([ 0, 11, 22, 33, 44])

In [18]:
a*100

array([  0, 100, 200, 300, 400])

In [23]:
b=np.arange(5)

In [24]:
b


array([0, 1, 2, 3, 4])

In [26]:
c=a+b

In [27]:
c

array([0, 2, 4, 6, 8])

In [28]:
c=a*b

In [29]:
c

array([ 0,  1,  4,  9, 16])

In [30]:
d=np.arange(3)
d+10

array([10, 11, 12])

In [32]:
c=a*d

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [36]:
#si le valeur suppéruer à 2  nous le remplace par TRUE sinonm, NOUS le remplace par false
a >=2

array([False, False,  True,  True,  True])